name: Update Daily Photo

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  update-photo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Fetch and save today's photo
      run: |
        curl -L "https://picsum.photos/1920/1080?grayscale" -o daily_photo.jpg

    - name: Update README.md with new photo path
      run: |
        sed -i 's|!\[\](.*)|![](daily_photo.jpg)|g' README.md

    - name: Commit and push changes if there are any
      run: |
        git config --global user.name "${{ secrets.LOG_USER }}"
        git config --global user.email "${{ secrets.LOG_MAIL }}"
        git diff --quiet || (git add README.md daily_photo.jpg && git commit -m "Update daily photo" && git push)
