name: Update Daily Photo

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-photo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update README.md with new photo URL
      run: |
        NEW_URL="https://picsum.photos/1920/1080?grayscale&random=$(date +%s)"
        sed -i "s|!\[\](.*)|![](${NEW_URL})|g" README.md

    - name: Commit and push changes if there are any
      run: |
        git config --global user.name '${{ secrets.LOG_USER }}'
        git config --global user.email '${{ secrets.LOG_MAIL }}'
        git diff --quiet || (git add README.md && git commit -m 'Update daily black-and-white photo' && git push)
